version: '3'
services:
  web:
    build: .
    environment:
      - PORT
      - DB_HOST
      - NODE_ENV
      - POSTGRES_PASSWORD
      - POSTGRES_USER
      - POSTGRES_DB=${POSTGRES_USER}
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - db
    volumes:
      - ./public:/public
  db:
    image: 'postgres:alpine'
    environment:
      - POSTGRES_PASSWORD
      - POSTGRES_USER
      - POSTGRES_DB=${POSTGRES_USER}
    volumes:
      - C:\Users\stave\code\lily-packs\pgdata:/var/lib/postgresql/data
    ports:
      - "${PGPORT}:${PGPORT}"
