version: '3'
services:
  web:
    build: .
    environment:
      - SERVERPORT
      - NODE_ENV
    ports:
      - "${SERVERPORT}:${SERVERPORT}"
  postgres:
    image: 'postgres:alpine'
    environment:
      - POSTGRES_PASSWORD
    ports:
      - ${PGPORT}
