version: '3'
services:
  web:
    build: .
    environment:
      - SERVERPORT
    ports:
      - "${SERVERPORT}:${SERVERPORT}"
  postgres:
    image: 'postgres:12.3'
    environment:
      - POSTGRES_PASSWORD
    ports:
      - ${PGPORT}
